### ISSUE TITLE
有没有‘’订阅’相关的API？

### ISSUE THREAD

**Issue by zhao-xiaohu** [YouHan26/wow#1]
有没有类似`dva`中的`subscriptions`的API？
因为通常业务逻辑是在`A页面`进行一些操作后，从别的页面再回到`A页面`时，state要清空。
所以`dva`中经常这样写：
```js
const initState = {
    ...
}

export default {
  state: initialState,
  subscriptions: {
    setup({ dispatch, history }) {
      history.listen(({ pathname }) => {
        if (pathname === '/page') {
          dispatch({ type: 'updateState', payload: initState })
          ...
        }
      })
    }
  }
  ...
}
```

如果没有的话，恐怕要下载页面组件的生命周期中了，这样页面组件不能写成纯函数组件，而且`initState`还要从`model`层去取，会有些麻烦。

**Comment by youhan26** [comment]
这个redux-observerable封装是不会集成类似subscriptions这些事情的。因为封装框架本身是依赖rxjs ，这些subscription完全可以通过自定义封装各种各样的observable 来提供 流， 同时封装框架这里是可以 横向拓展插件来 丰富功能。譬如，处理history跳转这些问题，配合react-router， 简单写个inori-history是很比较简单的。不知道有没有解释清楚

**Comment by zhao-xiaohu** [comment]
非常感谢你的回答，也很抱歉我现在才回复。
这个能用`observable`实现是毫无疑问的，而且也有人单独将`dva`中的`subscriptions`抽离出来[yax-router](https://github.com/d-band/yax-router)，但我觉得意义不是很大，"有没有、能不能实现" 和 "能否简单易用"是两码事，而`dva`也主要是解决了后者的问题。
而您说的"横向拓展插件"我还没能具体了解，不知道拓展之后的写法上是怎么样的。

**Comment by youhan26** [comment]
dva 这个框架无疑上手是简单易用的。但是简单易用的代价就是dva要自己维护一套react-router等库，封装这些库的api和流程。同时，框架使用者是无法享受到社区新版库带来的feature。
所以可以理解inori 就是剥离了上述这些，只是在写法和基础流程上做了一点点小改动的东西。脸皮厚一点来讲，相当于koa 较于 express。:p
上面你说的确实有道理，如果框架本身就提供类似subscription这些基础能力，无疑是更好的。
subscription这种基础api我会在下个版本加进去。
当然，如果你这边有想法，欢迎pr ~

**Comment by zhao-xiaohu** [comment]
同意你的观点。
`dva`作者也想把`router`从中剥离出来，但转身要把它整合到`umi`中去（吐血...）
离散些的话便于维护，但一定程度上和方便使用相斥，中间的权衡确实难以找到一个合适的平衡点。
最后，非常感谢！

**Comment by youhan26** [comment]
我准备这样设计api，你看一下
```js
// entry.js
import history from 'history/hashhistory'

inori.addSubscription('history', history.listen) // subscription name and event source

// model.js
subscriptions: {
     history: function(dispatch, location){
         // do something
     }
}
```
any comment ?
