### ISSUE TITLE
最近的更新引入了一些依赖，最好能更新一下package.json

### ISSUE THREAD

**Issue by dancancer** [YouHan26/wow#2]
最近的更新引入了一些依赖，最好能更新一下package.json, 另外RN要作为依赖引入是否可以做成可配置项？

**Comment by youhan26** [comment]
sorry，忘记更新了。
RN 我是想做成peerdependency， 然后库这边检测有没有 引入 RN 来判断当前环境。
关于配置项，有什么好想法么？

**Comment by dancancer** [comment]
如果这样的话RN版和web版是否分成两个入口会更合适些？类似 dva-no-router 的处理。

**Comment by youhan26** [comment]
@dancancer 感谢提出问题，这两天在忙其他的事情，回复慢了。
已拆分, [commit](https://github.com/YouHan26/wow/commit/696e2968a5565f96f4c99066f46c694bec0d4ca4)
明天，我在测试项目中测试一把，就发到npm上。
感谢

**Comment by youhan26** [comment]
web 直接安装最新版 inori 即可。

inori: 1.10.8
